FROM fedora

# ENV DEBIAN_FRONTEND noninteractive

# Update Ubuntu
# RUN dpkg --add-architecture i386

RUN mkdir /home/sicp

Add . /home/sicp
# RUN dpkg -i --force-architecture /home/sicp/stk_4.0.1-1_amd64.deb

CMD ["/bin/bash"]

